name    'staegi-prestashop'
version '0.0.1'
source  'UNKNOWN'
author  'Thomas Stägemann'
license 'Apache License, Version 2.0'
summary 'Prestashop puppet module'
description 'This is a Puppet module which installs a Prestashop.'
project_page 'http://github.com/staegi/puppet-prestashop'
dependency 'puppetlabs/mysql', '>= 2.3.1'
dependency 'puppetlabs/apache', '>= 1.1.1'
dependency 'jfryman/nginx', '>= 0.0.10'
